### ISSUE TITLE
docVisao - Elaboração

### ISSUE THREAD

**Issue by fjose90** [fjose123/LocationVAN#4]
1. Riscos
2. Suposições e dependências
3.Perspectiva do produto (dá uma visão geral de como o produto funcionará. Pode ser um protótipo de telas feito a mão ou não)
modelos:
https://drive.google.com/open?id=1Oba_CI5N7fjMONVMzgj-p-i6fxQJyc_U

**Comment by marcelorai** [comment]
Conclusão dos tópicos dessa etapa de elaboração.

**Comment by fjose90** [comment]
@marcelorai  que fecha sou eu moral!
